<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: itens.proto

namespace Canary\Protobuf\Itemsserialization;

use UnexpectedValueException;

/**
 * Protobuf type <code>Canary.protobuf.itemsserialization.ATTRIBUTE_TYPE</code>
 */
class ATTRIBUTE_TYPE
{
    /**
     * Generated from protobuf enum <code>ATTRIBUTE_TYPE_STRING = 0;</code>
     */
    const ATTRIBUTE_TYPE_STRING = 0;
    /**
     * Generated from protobuf enum <code>ATTRIBUTE_TYPE_NUMERIC = 1;</code>
     */
    const ATTRIBUTE_TYPE_NUMERIC = 1;
    /**
     * Generated from protobuf enum <code>ATTRIBUTE_TYPE_FLOAT = 2;</code>
     */
    const ATTRIBUTE_TYPE_FLOAT = 2;
    /**
     * Generated from protobuf enum <code>ATTRIBUTE_TYPE_BOOLEAN = 3;</code>
     */
    const ATTRIBUTE_TYPE_BOOLEAN = 3;
    /**
     * Generated from protobuf enum <code>ATTRIBUTE_TYPE_POSITION = 4;</code>
     */
    const ATTRIBUTE_TYPE_POSITION = 4;

    private static $valueToName = [
        self::ATTRIBUTE_TYPE_STRING => 'ATTRIBUTE_TYPE_STRING',
        self::ATTRIBUTE_TYPE_NUMERIC => 'ATTRIBUTE_TYPE_NUMERIC',
        self::ATTRIBUTE_TYPE_FLOAT => 'ATTRIBUTE_TYPE_FLOAT',
        self::ATTRIBUTE_TYPE_BOOLEAN => 'ATTRIBUTE_TYPE_BOOLEAN',
        self::ATTRIBUTE_TYPE_POSITION => 'ATTRIBUTE_TYPE_POSITION',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

