<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: itens.proto

namespace Canary\Protobuf\Itemsserialization;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Canary.protobuf.itemsserialization.Item</code>
 */
class Item extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional uint32 pid = 1;</code>
     */
    protected $pid = null;
    /**
     * Generated from protobuf field <code>optional uint32 sid = 2;</code>
     */
    protected $sid = null;
    /**
     * Generated from protobuf field <code>optional uint32 id = 3;</code>
     */
    protected $id = null;
    /**
     * Generated from protobuf field <code>optional uint32 subtype = 4;</code>
     */
    protected $subtype = null;
    /**
     * Generated from protobuf field <code>repeated .Canary.protobuf.itemsserialization.Attribute attribute = 5;</code>
     */
    private $attribute;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $pid
     *     @type int $sid
     *     @type int $id
     *     @type int $subtype
     *     @type array<\Canary\Protobuf\Itemsserialization\Attribute>|\Google\Protobuf\Internal\RepeatedField $attribute
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Itens::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 pid = 1;</code>
     * @return int
     */
    public function getPid()
    {
        return isset($this->pid) ? $this->pid : 0;
    }

    public function hasPid()
    {
        return isset($this->pid);
    }

    public function clearPid()
    {
        unset($this->pid);
    }

    /**
     * Generated from protobuf field <code>optional uint32 pid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPid($var)
    {
        GPBUtil::checkUint32($var);
        $this->pid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 sid = 2;</code>
     * @return int
     */
    public function getSid()
    {
        return isset($this->sid) ? $this->sid : 0;
    }

    public function hasSid()
    {
        return isset($this->sid);
    }

    public function clearSid()
    {
        unset($this->sid);
    }

    /**
     * Generated from protobuf field <code>optional uint32 sid = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSid($var)
    {
        GPBUtil::checkUint32($var);
        $this->sid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 id = 3;</code>
     * @return int
     */
    public function getId()
    {
        return isset($this->id) ? $this->id : 0;
    }

    public function hasId()
    {
        return isset($this->id);
    }

    public function clearId()
    {
        unset($this->id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 subtype = 4;</code>
     * @return int
     */
    public function getSubtype()
    {
        return isset($this->subtype) ? $this->subtype : 0;
    }

    public function hasSubtype()
    {
        return isset($this->subtype);
    }

    public function clearSubtype()
    {
        unset($this->subtype);
    }

    /**
     * Generated from protobuf field <code>optional uint32 subtype = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setSubtype($var)
    {
        GPBUtil::checkUint32($var);
        $this->subtype = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Canary.protobuf.itemsserialization.Attribute attribute = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttribute()
    {
        return $this->attribute;
    }

    /**
     * Generated from protobuf field <code>repeated .Canary.protobuf.itemsserialization.Attribute attribute = 5;</code>
     * @param array<\Canary\Protobuf\Itemsserialization\Attribute>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttribute($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Canary\Protobuf\Itemsserialization\Attribute::class);
        $this->attribute = $arr;

        return $this;
    }

}

