<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: itens.proto

namespace Canary\Protobuf\Itemsserialization;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Canary.protobuf.itemsserialization.ItemsSerialization</code>
 */
class ItemsSerialization extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Canary.protobuf.itemsserialization.Item item = 1;</code>
     */
    private $item;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Canary\Protobuf\Itemsserialization\Item>|\Google\Protobuf\Internal\RepeatedField $item
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Itens::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Canary.protobuf.itemsserialization.Item item = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItem()
    {
        return $this->item;
    }

    /**
     * Generated from protobuf field <code>repeated .Canary.protobuf.itemsserialization.Item item = 1;</code>
     * @param array<\Canary\Protobuf\Itemsserialization\Item>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItem($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Canary\Protobuf\Itemsserialization\Item::class);
        $this->item = $arr;

        return $this;
    }

}

